// layout contiene todo lo que un html inicial de otro framework tiene, solo que en JS
import Navegacion from '@/components/Navegacion'

export const metadata = {
  title: 'Practica NextJs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Instalacion de bootstrap desde cdn */}
        <link rel='stylesheet' href='https://bootswatch.com/5/sketchy/bootstrap.min.css'/>
      </head>
      <body>
        <Navegacion/>
        <div className='container p-4'>
          {children}
        </div>
      </body>
    </html>
  )
}
